---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: nensiravaliya28/catalog:latest
          env:
            - name: DATABASE_HOST
              value: mysql-service
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_PASSWORD
          ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  # Use a port in the range 30000-32767

