---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: nensiravaliya28/order:latest
          env:
            - name: DATABASE_HOST
              value: mysql-service
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002  # Use a port in the range 30000-32767

