# Base image
FROM nginx:alpine

# Copy static files to Nginx's default public folder
COPY ./frontend /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]

