---
- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  retries: 3
  delay: 10

- name: Install Nginx
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: present
  retries: 3
  delay: 10

- name: Deploy Nginx Configuration
  become: yes
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Deploy Static Content
  become: yes
  ansible.builtin.copy:
    src: static/
    dest: /var/www/html/
    mode: '0755'

- name: Start and Enable Nginx
  become: yes
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
