apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: static-web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: static-web-app 
  minReplicas: 1 
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50  
