apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init-db.sql: |
    CREATE DATABASE mydatabase;
    USE mydatabase;

    CREATE TABLE example (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  API_URL: "http://catalog-service:3000"
  OTHER_CONFIG: "value"

