---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Create symbolic link to sites-enabled
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx reload
  service:
    name: nginx
    state: reloaded  # Reload Nginx to apply changes
    enabled: yes
