---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install MySQL and dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev

- name: Start and enable MySQL service
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL user (medium_post)
  become: yes
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Create medium_db
  become: yes
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Enable remote login to MySQL
  become: yes
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify:
    - Restart mysql
